spring.application.name=FoodDash
spring.datasource.url=jdbc:mysql://localhost:3306/fooddash
spring.datasource.username=root
spring.datasource.password=Hrishi@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key.id=rzp_test_Sbm0uHW9kQHEjr
razorpay.key.secret=6TN2gW5kSqJjngspJnrnpsF9
#razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET}
app.payment.currency=INR

cloudinary.cloud-name=dzw5a4vfk
cloudinary.api-key=163846126113447
cloudinary.api-secret=aetUFQdJ9K8OegRC7iVbzj1xXOM


# Default logging level
logging.level.root=INFO

# Your app package (more detailed logs)
logging.level.com.app.fooddash=DEBUG